# Generated by Django 3.0.4 on 2020-04-03 15:33

from django.conf import settings
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20200328_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=models.SET(events.models.get_sentinel_user), related_name='host_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, default='https://i.imgur.com/yejzBet.png', null=True, verbose_name='Picture url'),
        ),
    ]
