# Generated by Django 3.0.4 on 2020-04-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200407_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, default='https://i.imgur.com/DHM869r.png', null=True, verbose_name='Picture url'),
        ),
    ]
