# Generated by Django 3.0.4 on 2020-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200405_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, default='https://i.imgur.com/bq3Bb34.png', null=True, verbose_name='Picture url'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_access_token',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='stripe_access_token'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_user_id',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='stripe_user_id'),
        ),
    ]
