language: python
python:
  - "3.8.1"
services:
  - postgresql
env:
  - DJANGO=3.0.4 DB=postgres
global:
  - PGPORT=5432
before_install:
  - sudo service postgresql stop
  - sudo apt-get --yes remove postgresql-10-postgis-2.4
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-12-postgis-2.5-scripts postgresql-12 postgresql-client-12 postgresql-12-postgis-2.5
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/12/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/12/main
  - sudo cp /etc/postgresql/{10,12}/main/pg_hba.conf
  - sudo service postgresql restart 12
install:
  - pip install -r requirements.txt
before_script:
  - cp ./eventshow/local_settings.example.py ./eventshow/local_settings.py
  - export PATH="/usr/lib/postgresql/12/bin:$PATH"
  - psql -U postgres -c "CREATE USER showman WITH PASSWORD 'showman'"
  - psql -U postgres -c "ALTER USER showman CREATEDB"
  - psql -U postgres -c "CREATE DATABASE eventshow OWNER showman"
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runscript seed
script:
  - travis_wait 20 python manage.py test
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
branches:
  only:
    - master
    - dev